name: Build
on: [push]

jobs:
  build_ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS application
        run: flutter build ios --no-codesign

  build_android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android application
        run: flutter build apk

  build_web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web application
        run: flutter build web

  analyze_project:
    needs: [ build_web, build_android, build_ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Flutter analyze
        run: flutter analyze
  test_publish:
    needs: analyze_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        id: flutter
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: test flutter pub publish --dry-run
        run: flutter pub publish --dry-run
